spring:
  datasource:
    url: jdbc:mysql://cdb-2i06sqln.gz.tencentcdb.com:10098/csi?useUnicode=true&characterEncoding=utf-8&useSSL=true&&serverTimezone=GMT
    username: root
    password: yzj578692102
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB
    port:
      8080
mybatis:
  type-aliases-package: ynu.csistaffsystem.dto
  mapper-locations: classpath:mapper/*.xml
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



